name: Java CI with Maven

# This workflow runs on pushes to the 'main' branch and on any pull request
on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up the Java version we need (e.g., 17)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Step 3: Run the Maven build and test command
      # 'package' goal automatically compiles and runs the 'test' phase.
      # -B flag runs Maven in non-interactive (batch) mode.
      - name: Build and run tests with Maven
        run: mvn -B package --file pom.xml # Use root pom.xml for multi-module